[project]
name = "localrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium[other]>=1.2.0",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "tensorboard>=2.19.0",
    "wandb>=0.21.0",
]
